#!/usr/bin/env bash

########################
# Author: Shinichi Okada
# Date: 2021-05-22
###########################

unset user dir repo license_url

script_name=$(basename "$0")
dir=""
version="0.2.5"

usage() {
    cat <<EOF

Script name: $script_name

Description:
============

This script automate creating git repo.
This will create a dir, add a license, README file, run git init and push to Github. 

If a language is added, it will try to add the .gitignore.
Choose SSH as the default git protocol.

List of .gitignore supported by Github
======================================

See https://github.com/github/gitignore

Dependencies:
=============

- gh, GitHub CLI https://cli.github.com/manual/
- yq, https://github.com/mikefarah/yq
- jq

Usage:
======

$script_name [ -l | --lang programming_language ] [ -d | --dir directory ] [ -h | --help | -v | --version]

Examples:
=========

    $script_name -l python -d newrepo
    $script_name -d newrepo
    # in a directory
    $script_name -d .
    # Show help
    $script_name -h
    # Show version
    $script_name -v
EOF
}

while (($# > 0)); do # while arguments count>0
    case "$1" in
    -l | --lang)
        prog_lang=$2
        shift
        ;;
    -d | --dir)
        dir=$2
        shift 2
        ;;
    -h | --help)
        usage
        exit
        ;;
    -v | --version)
        echo ${version}
        exit
        ;;
    *) # unknown flag/switch
        POSITIONAL+=("$1")
        shift
        ;;
    esac
done

############# Main body ############
# check if you are logged in github
if [[ $(gh auth status) -eq 1 ]]; then
    # not logged-in
    echo ">>> You must logged in. Use 'gh auth login'"
    exit 1
fi

# don't allow to create a git repo in the ~ (HOME)
# user may use . in the HOME
cwd=$(pwd)
if [[ (${dir} = "$HOME") || ($cwd = "$HOME" && ${dir} = ".") ]]; then
    echo "This script doesn't allow to create a git repo in the home directory."
    echo "Use another directory."
    exit 1
fi

# if dir is empty exit
if [[ -z ${dir} ]]; then
    echo "You must set -d dir_name."
    exit
fi

# check if you have Github CLI
if [ ! "$(command -v gh)" ]; then
    echo "Please install Github CLI from https://cli.github.com/manual/."
    exit 2
fi

# check if you have yq
if [ ! "$(command -v yq)" ]; then
    echo "Please install yq from https://github.com/mikefarah/yq."
    exit 2
fi

# check if you have yq
if [ ! "$(command -v jq)" ]; then
    echo "Please install jq from https://stedolan.github.io/jq/."
    exit 2
fi

# Directory path. If dir is . then use pwd
if [[ ${dir} = "." ]]; then
    dir=$(pwd)
else
    echo ">>> Creating ${dir}."
    dir="$(pwd)/$dir"
    mkdir -p "$dir" || exit
    # cd "$dir" || exit
fi

# user=$(yq e '."github.com".user' "$HOME"/.config/gh/hosts.yml)

repo=$(basename "${dir}")
# license_url="mit"
# echo ">>> Your github username is ${user}."
echo ">>> Your new repo name is ${repo}."

# echo "$dir"
cd "$dir" || exit


# README
echo ">>> Creating README.md."
printf "# %s \n
## Overview\n\n
## Requirement\n\n
## Usage\n\n
## Features\n\n
## Reference\n\n
## Author\n\n
## License

Please see license.txt.\n" "${repo}" >README.md

echo ">>> Creating your ${repo} in remote."
gh repo create "${repo}" 2>/dev/null
echo ">>> Adding README.md."
git add .
echo ">>> Commiting ..."
git commit -m "README added."
echo ">>> Pushing local repo to the remote."
git push -u origin main
exit 0
